# Generated by Django 5.0.6 on 2024-06-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unidad', models.CharField(max_length=100)),
                ('tipo_bien_servicio', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_adquisicion', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('documentacion', models.TextField()),
            ],
        ),
    ]
